services:
  - type: web
    name: kdu-global-chatbot
    runtime: python
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.4